//Script,onDataLoad
// GENERATED by tools/stamp-runtime.mjs - do not edit by hand.
//
// Publishes the content hash of every file in runtime/ into the page, so a test
// can prove the browser loaded the revision it is being asked to verify rather
// than a copy the CDN held back. See docs/testing-with-playwright.md.
window.pbsRuntimeBuild = {
    combined: "a0843913",
    files: {
            "activeWatcher.js": "ed8bd27c",
            "chatDestination.js": "a4854ebf",
            "deferGuard.js": "aa11d4a6",
            "devLoader.js": "f92655d7",
            "displayHCP.js": "1c4f497c",
            "onAnyMutation-config.js": "59ce4706",
            "onAnyMutation-dropdown.js": "ae59581a",
            "onAnyMutation-hcp.js": "bb02035a",
            "panelStyle.js": "72c6b362",
            "pbsDynamicLayout.js": "b3a33398",
            "plugins/BBAcompare.js": "6ba9e4d9",
            "setDealerCode-polling.js": "67f53d85",
            "startTable.js": "a6b0f554",
            "tabDelegation.js": "a86c1059",
            "toggleRotate.js": "b345ad09"
}
};
console.log("[PBS] runtime build " + window.pbsRuntimeBuild.combined
    + " (" + Object.keys(window.pbsRuntimeBuild.files).length + " files)");
//Script
