#!/usr/bin/env node
// Regenerate runtime/buildStamp.js from the CONTENT of the runtime files.
//
// The problem this solves: runtime/ is fetched from raw.githubusercontent, which
// caches for ~5 minutes. A test run started soon after a push exercises the OLD
// file, and the failure looks exactly like a broken fix. That produced three
// wrong diagnoses in a single day, twice after the trap had been written down -
// because "did the browser load what I just pushed?" was a judgement call.
//
// Now it is a comparison. Each file's short content hash is published into the
// page, and a test compares what loaded against what is on disk.
//
// Forgetting to run this is caught too: the stamp would then disagree with the
// files it claims to describe, and the check fails the same way staleness does.
//
//   node tools/stamp-runtime.mjs          rewrite runtime/buildStamp.js
//   node tools/stamp-runtime.mjs --check  exit 1 if it is out of date
import { createHash } from 'crypto';
import { readdirSync, readFileSync, writeFileSync, statSync } from 'fs';
import { join, relative } from 'path';

const ROOT = new URL('..', import.meta.url).pathname;
const RUNTIME = join(ROOT, 'runtime');
const OUT = join(RUNTIME, 'buildStamp.js');
const SELF = 'buildStamp.js';

const short = (buf) => createHash('sha256').update(buf).digest('hex').slice(0, 8);

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) return walk(p);
    return name.endsWith('.js') && name !== SELF ? [p] : [];
  });
}

const files = walk(RUNTIME).sort();
const stamps = {};
for (const f of files) stamps[relative(RUNTIME, f)] = short(readFileSync(f));
const combined = short(Object.entries(stamps).map(([k, v]) => k + ':' + v).join('\n'));

const body = `//Script,onDataLoad
// GENERATED by tools/stamp-runtime.mjs - do not edit by hand.
//
// Publishes the content hash of every file in runtime/ into the page, so a test
// can prove the browser loaded the revision it is being asked to verify rather
// than a copy the CDN held back. See docs/testing-with-playwright.md.
window.pbsRuntimeBuild = {
    combined: ${JSON.stringify(combined)},
    files: ${JSON.stringify(stamps, null, 8).replace(/\n(\s+)/g, '\n    $1').replace(/\n {4}}$/, '\n    }')}
};
console.log("[PBS] runtime build " + window.pbsRuntimeBuild.combined
    + " (" + Object.keys(window.pbsRuntimeBuild.files).length + " files)");
//Script
`;

if (process.argv.includes('--check')) {
  let current = '';
  try { current = readFileSync(OUT, 'utf8'); } catch {}
  if (current !== body) {
    console.error('runtime/buildStamp.js is out of date - run: node tools/stamp-runtime.mjs');
    process.exit(1);
  }
  console.log('runtime/buildStamp.js is current (' + combined + ', ' + files.length + ' files)');
} else {
  writeFileSync(OUT, body);
  console.log('wrote runtime/buildStamp.js  combined=' + combined + '  files=' + files.length);
}
